### ISSUE TITLE
test24InHerd failed in module 6 assignment

### ISSUE THREAD

**Issue by Neeraj-Prakash** [graffixnyc/Coursera_Java_For_Android#1]
your code seem to fail the "test24InHerd" test. It passes all other tests but this one.

In "HerdManager.java":
also in the section wher you are finding out what direction to take. shouldn't you take "direction = MyRandom.nextInt(2)" in the else part?

you are also not transferring the snails when the gate direction is IN.

check the code again and update it please.

**Comment by graffixnyc** [comment]
How would you know it failed the test unless you tried submitting my work as yours? You would only know it failed one of their tests if you tried submitting it. I have no interest in updating 3+ year code so someone else can submit it as their own and cheat. I never claimed my code for this course was perfect and I did have a mistake here and there.

**Comment by Neeraj-Prakash** [comment]
I was not submitting your code. I was just running the unit test program provided by them.
I had written the code and was getting similar error as your code. I tried but was not getting the problem. So I was looking in the internet for any help. Then I found your code. But it gave the same error.
Anyways I have debugged my code and passed the unit tests and submitted my assignment. 
Thanks.
